spring:
  profiles:
    default: default
  datasource:
    url: jdbc:mysql://localhost:3306/giftibox?useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: 1234
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        dialect: org.hibernate.dialect.MySQLDialect
    defer-datasource-initialization: true
  sql:
    init:
      mode: always
      schema-locations: classpath:sql/table_schema.sql
      data-locations: classpath:sql/data.sql

logging:
  level:
    org:
      hibernate: DEBUG