spring:
  datasource:
    url: jdbc:mysql://localhost:3306/gifticon
    username: root
    password: 1234
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
        show_sql: true
    defer-datasource-initialization: true
  sql:
    init:
      mode: always
      schema-locations: classpath:sql/table_schema.sql
      data-locations: classpath:sql/data.sql