-- 테이블 초기화
DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS gifticon;

-- user 테이블
CREATE TABLE users
(
    id            BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    email         VARCHAR(255) UNIQUE NOT NULL,
    password VARCHAR(255)        NOT NULL
-- ,
--     created_at    TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
--     updated_at    TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);


CREATE TABLE gifticon
(
    id BIGINT AUTO_INCREMENT PRIMARY KEY
);