server:
  port: 8082

spring:
  profiles:
    default: default
  datasource:
    url: jdbc:mysql://localhost:3306/giftibox?useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: 1234
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect